/* eslint-disable @next/next/no-img-element */

import type { Metadata } from "next";
import Favicon from "/public/favicon.ico";
import "../../styles/global.css";
import Footer from "@/components/common/common-footer/Footer";
import Header from "@/components/common/Header";

export const metadata: Metadata = {
  title: "Home page | Petfoster",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header dynamic={false} />
      <main className="mt-[85px]">{children}</main>
      <Footer />
    </>
  );
}
