import BoxTitle from "@/components/boxs/BoxTitle";
import NavProfile from "@/components/common/common-headers/NavProfile";
import { Avatar, Grid2 } from "@mui/material";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Profile Page | Petfoster",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <BoxTitle locationTitle="left" title="MY ACCOUNT">
      <Grid2 container spacing={"10px"} className="min-h-[518px]">
        <Grid2 size={{ sm: 12, md: 4, lg: 3 }}>
          <NavProfile />
        </Grid2>
        <Grid2 size={{ sm: 12, md: 8, lg: 9 }}>
          <div className="h-full">{children}</div>
        </Grid2>
      </Grid2>
    </BoxTitle>
  );
}
