import { Metadata } from "next";
import React, { ReactNode } from "react";
import Favicon from "/public/favicon.ico";
import AdorableLayout from "@/components/layouts/AdorableSnapshotsLayout";
import Header from "@/components/common/Header";

export interface IAdorableSnapshotsLayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Adorable Snapshots | Petfoster",
  description: "Generated by create next app",
  icons: [{ rel: "icon", url: Favicon.src }],
};

// Alias AdorableSnapshotsLayout as PrimaryLayout
const PrimaryLayout = AdorableLayout;

export default function AdorableSnapshotsLayout({
  children,
}: IAdorableSnapshotsLayoutProps) {
  return (
    <>
      <Header dynamic={false} />
      <main className="mt-[85px]">
        <PrimaryLayout>{children}</PrimaryLayout>
      </main>
    </>
  );
}
